<?php
/**
 * Data Machine — AGENTS.md composition (gated).
 *
 * AGENTS.md is the agent-instruction file that lives at the WordPress install
 * root. Unlike SITE.md / NETWORK.md (always composed), AGENTS.md composition is
 * **gated default-OFF** behind the `DATAMACHINE_COMPOSE_AGENTS_MD` wp-config
 * constant. The gate is constant-only — no option fallback — because the signal
 * has exactly one rightful writer (the external coding-agent runtime installer),
 * and an option would be a second source of truth.
 *
 * Resolution: `defined('DATAMACHINE_COMPOSE_AGENTS_MD') && DATAMACHINE_COMPOSE_AGENTS_MD`.
 *
 * - OFF (constant unset or false): core registers NO AGENTS.md composable file
 *   and NO AGENTS.md sections — zero footprint, reproducing the historical
 *   no-noise behavior on installs with no coding agent.
 * - ON: core registers the AGENTS.md composable file (so `wp datamachine memory
 *   compose AGENTS.md` writes it and auto-regeneration keeps it fresh) and the
 *   core-owned sections, including concise Data Machine routing and discovery
 *   guidance. The live CLI help remains the complete command authority.
 *
 * Why composition lives in core: core already owns SectionRegistry,
 * MemoryFileRegistry, ComposableFileGenerator, ComposableFileInvalidation, and
 * CliCommandIntrospector. AGENTS.md previously lived in data-machine-code only
 * for noise-gating — but gating is not ownership. Core owns the composition; the
 * gate decides whether it runs. (Extra-Chill/data-machine#2640, #2613.)
 *
 * @package DataMachine
 */

defined( 'ABSPATH' ) || exit;

use DataMachine\Engine\AI\MemoryFileRegistry;
use DataMachine\Engine\AI\SectionRegistry;

/**
 * Whether AGENTS.md composition is enabled for this install.
 *
 * Constant-only gate. The external coding-agent runtime installer writes the
 * constant into wp-config (mirroring the `DATAMACHINE_WORKSPACE_PATH` writer);
 * core never writes it. Absence means "no coding agent lives here" → zero
 * AGENTS.md footprint.
 *
 * @return bool
 */
function datamachine_agents_md_enabled(): bool {
	return defined( 'DATAMACHINE_COMPOSE_AGENTS_MD' ) && DATAMACHINE_COMPOSE_AGENTS_MD;
}

/**
 * Register AGENTS.md as a composable memory file — gated.
 *
 * Mirrors the SITE.md / NETWORK.md registration in
 * datamachine_register_default_memory_files(), but only when the gate is on so
 * an install with no coding agent never advertises or writes AGENTS.md.
 *
 * @return void
 */
function datamachine_register_agents_md_file(): void {
	if ( ! datamachine_agents_md_enabled() ) {
		return;
	}

	MemoryFileRegistry::register(
		'AGENTS.md',
		5,
		array(
			'layer'           => MemoryFileRegistry::LAYER_SHARED,
			'protected'       => true,
			'composable'      => true,
			'convention_path' => 'AGENTS.md',
			'modes'           => array( MemoryFileRegistry::MODE_ALL ),
			'label'           => 'Agent Instructions',
			'description'     => 'Auto-generated from registered sections. Regenerate via: wp datamachine memory compose AGENTS.md',
		)
	);
}

/**
 * Register core-owned AGENTS.md sections — gated.
 *
 * Fires on `datamachine_sections` (once per request, lazily). When the gate is
 * off this is a no-op, so even if a stray AGENTS.md file exists it composes to
 * nothing from core.
 *
 * Sections registered here describe Data Machine itself. The external coding
 * runtime installer owns generic WordPress coding guidance, while Data Machine
 * Code owns its workspace lifecycle section.
 *
 * @return void
 */
function datamachine_register_agents_md_sections(): void {
	if ( ! datamachine_agents_md_enabled() ) {
		return;
	}

	$wp = datamachine_agents_md_wp_cli_cmd();

	$core_meta = array(
		'owner'      => 'data-machine',
		'freshness'  => 'static',
		'conditions' => 'Registered when DATAMACHINE_COMPOSE_AGENTS_MD is enabled.',
	);

	// Auto-generated marker.
	SectionRegistry::register(
		'AGENTS.md',
		'auto-generated-marker',
		0,
		function () use ( $wp ) {
			$generated_at = gmdate( 'c' );
			return <<<MD
<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->
<!-- generated at: {$generated_at} -->
<!-- edit registered sections in their owning plugins, not this file -->
MD;
		},
		array_merge( $core_meta, array( 'freshness' => 'generated' ) )
	);

	// Data Machine routing and discovery guidance.
	SectionRegistry::register(
		'AGENTS.md',
		'datamachine',
		10,
		'datamachine_agents_md_render_datamachine_section',
		array(
			'owner'      => 'data-machine',
			'freshness'  => 'static',
			'conditions' => 'Registered when DATAMACHINE_COMPOSE_AGENTS_MD is enabled.',
		)
	);

	// Multisite (only on multisite installs).
	if ( is_multisite() ) {
		SectionRegistry::register(
			'AGENTS.md',
			'multisite',
			40,
			function () use ( $wp ) {
				return <<<MD
## Multisite

This is a WordPress multisite. Use `--url` to target specific sites:
```
{$wp} --url=site.example.com <command>
```
Without `--url`, commands default to the main site.
MD;
			},
			array_merge( $core_meta, array( 'conditions' => 'Only registered on multisite installs when the gate is enabled.' ) )
		);
	}
}

/**
 * Render the `## Data Machine` AGENTS.md section.
 *
 * Persistent agent context carries ownership, routing, and discovery guidance.
 * The live WP-CLI help remains authoritative for the complete command map.
 *
 * @return string
 */
function datamachine_agents_md_render_datamachine_section(): string {
	$wp = datamachine_agents_md_wp_cli_cmd();

	return <<<MD
## Data Machine

Data Machine is the WordPress-side operating layer for memory, automation, content operations, communication, agent configuration, and system execution.

**Default routing**
- Memory and composed context: `{$wp} datamachine memory --help`
- Flows and pipelines: `{$wp} datamachine flows` and `{$wp} datamachine pipelines`
- Job and worker state: `{$wp} datamachine jobs --help` and `{$wp} datamachine worker --help`
- Content and media operations: `{$wp} datamachine posts --help`, `{$wp} datamachine blocks --help`, or `{$wp} datamachine image --help`
- Communication and approval queues: `{$wp} datamachine email --help` and `{$wp} datamachine pending-actions --help`
- Agent and system configuration: `{$wp} datamachine agent --help` and `{$wp} datamachine system --help`

**Discovery**
Use `{$wp} datamachine --help` for the live command map and `{$wp} datamachine <command> --help` for the current options and subcommands.
MD;
}

/**
 * Resolve the WP-CLI command prefix for the current environment.
 *
 * @return string
 */
function datamachine_agents_md_wp_cli_cmd(): string {
	$parts = array( 'wp' );

	if ( function_exists( 'posix_geteuid' ) && 0 === posix_geteuid() ) {
		$parts[] = '--allow-root';
	}

	$abspath = rtrim( ABSPATH, '/' );
	if ( '/var/www/html' !== $abspath ) {
		$parts[] = '--path=' . $abspath;
	}

	return apply_filters( 'datamachine_wp_cli_cmd', implode( ' ', $parts ) );
}

// Sections register on `datamachine_sections` (fired lazily, once per request,
// when a composable file is generated). The AGENTS.md composable-file
// registration itself is wired alongside the other default memory files in
// datamachine_register_default_memory_files() (inc/bootstrap.php), mirroring how
// SITE.md / NETWORK.md register — so all default memory files share one
// registration path on `plugins_loaded`.
add_action( 'datamachine_sections', 'datamachine_register_agents_md_sections' );
