<?php
/**
 * Data Machine — AGENTS.md composition (gated).
 *
 * AGENTS.md is the agent-instruction file that lives at the WordPress install
 * root. Unlike SITE.md / NETWORK.md (always composed), AGENTS.md composition is
 * **gated default-OFF** behind the `DATAMACHINE_COMPOSE_AGENTS_MD` wp-config
 * constant. The gate is constant-only — no option fallback — because the signal
 * has exactly one rightful writer (the external coding-agent runtime installer),
 * and an option would be a second source of truth.
 *
 * Resolution: `defined('DATAMACHINE_COMPOSE_AGENTS_MD') && DATAMACHINE_COMPOSE_AGENTS_MD`.
 *
 * - OFF (constant unset or false): core registers NO AGENTS.md composable file
 *   and NO AGENTS.md sections — zero footprint, reproducing the historical
 *   no-noise behavior on installs with no coding agent.
 * - ON: core registers the AGENTS.md composable file (so `wp datamachine memory
 *   compose AGENTS.md` writes it and auto-regeneration keeps it fresh) and the
 *   core-owned sections, including the `datamachine` section whose command list
 *   is REFLECTED from core's registered command classes (never hand-typed).
 *
 * Why composition lives in core: core already owns SectionRegistry,
 * MemoryFileRegistry, ComposableFileGenerator, ComposableFileInvalidation, and
 * CliCommandIntrospector. AGENTS.md previously lived in data-machine-code only
 * for noise-gating — but gating is not ownership. Core owns the composition; the
 * gate decides whether it runs. (Extra-Chill/data-machine#2640, #2613.)
 *
 * @package DataMachine
 */

defined( 'ABSPATH' ) || exit;

use DataMachine\Engine\AI\MemoryFileRegistry;
use DataMachine\Engine\AI\SectionRegistry;
use DataMachine\Cli\CommandRegistry;

/**
 * Whether AGENTS.md composition is enabled for this install.
 *
 * Constant-only gate. The external coding-agent runtime installer writes the
 * constant into wp-config (mirroring the `DATAMACHINE_WORKSPACE_PATH` writer);
 * core never writes it. Absence means "no coding agent lives here" → zero
 * AGENTS.md footprint.
 *
 * @return bool
 */
function datamachine_agents_md_enabled(): bool {
	return defined( 'DATAMACHINE_COMPOSE_AGENTS_MD' ) && DATAMACHINE_COMPOSE_AGENTS_MD;
}

/**
 * Register AGENTS.md as a composable memory file — gated.
 *
 * Mirrors the SITE.md / NETWORK.md registration in
 * datamachine_register_default_memory_files(), but only when the gate is on so
 * an install with no coding agent never advertises or writes AGENTS.md.
 *
 * @return void
 */
function datamachine_register_agents_md_file(): void {
	if ( ! datamachine_agents_md_enabled() ) {
		return;
	}

	MemoryFileRegistry::register(
		'AGENTS.md',
		5,
		array(
			'layer'           => MemoryFileRegistry::LAYER_SHARED,
			'protected'       => true,
			'composable'      => true,
			'convention_path' => 'AGENTS.md',
			'modes'           => array( MemoryFileRegistry::MODE_ALL ),
			'label'           => 'Agent Instructions',
			'description'     => 'Auto-generated from registered sections. Regenerate via: wp datamachine memory compose AGENTS.md',
		)
	);
}

/**
 * Register core-owned AGENTS.md sections — gated.
 *
 * Fires on `datamachine_sections` (once per request, lazily). When the gate is
 * off this is a no-op, so even if a stray AGENTS.md file exists it composes to
 * nothing from core.
 *
 * Sections registered here describe Data Machine itself. The external coding
 * runtime installer owns generic WordPress coding guidance, while Data Machine
 * Code owns its `datamachine-code` section and workspace inventory.
 *
 * @return void
 */
function datamachine_register_agents_md_sections(): void {
	if ( ! datamachine_agents_md_enabled() ) {
		return;
	}

	$wp = datamachine_agents_md_wp_cli_cmd();

	$core_meta = array(
		'owner'      => 'data-machine',
		'freshness'  => 'static',
		'conditions' => 'Registered when DATAMACHINE_COMPOSE_AGENTS_MD is enabled.',
	);

	// Auto-generated marker.
	SectionRegistry::register(
		'AGENTS.md',
		'auto-generated-marker',
		0,
		function () use ( $wp ) {
			$generated_at = gmdate( 'c' );
			return <<<MD
<!-- regenerated by: {$wp} datamachine memory compose AGENTS.md -->
<!-- generated at: {$generated_at} -->
<!-- edit registered sections in their owning plugins, not this file -->
MD;
		},
		array_merge( $core_meta, array( 'freshness' => 'generated' ) )
	);

	// The reflected `datamachine` command-surface section.
	SectionRegistry::register(
		'AGENTS.md',
		'datamachine',
		10,
		'datamachine_agents_md_render_datamachine_section',
		array(
			'owner'      => 'data-machine',
			'freshness'  => 'snapshot',
			'conditions' => 'Registered when DATAMACHINE_COMPOSE_AGENTS_MD is enabled; command list reflected from registered command classes.',
		)
	);

	// Multisite (only on multisite installs).
	if ( is_multisite() ) {
		SectionRegistry::register(
			'AGENTS.md',
			'multisite',
			40,
			function () use ( $wp ) {
				return <<<MD
## Multisite

This is a WordPress multisite. Use `--url` to target specific sites:
```
{$wp} --url=site.example.com <command>
```
Without `--url`, commands default to the main site.
MD;
			},
			array_merge( $core_meta, array( 'conditions' => 'Only registered on multisite installs when the gate is enabled.' ) )
		);
	}
}

/**
 * Render the `## Data Machine` AGENTS.md section.
 *
 * The command list is reflected from CommandRegistry::map() — the same map that
 * feeds WP-CLI registration in Bootstrap.php — so adding or renaming a
 * `datamachine` subcommand surfaces here automatically with no heredoc edit, and
 * a command removed from core (e.g. the now-relocated `analytics`) disappears
 * from the documentation by construction.
 *
 * @return string
 */
function datamachine_agents_md_render_datamachine_section(): string {
	$wp = datamachine_agents_md_wp_cli_cmd();

	$lines   = array();
	$lines[] = '## Data Machine';
	$lines[] = '';
	$lines[] = 'Data Machine is your operating layer — memory, automation, and orchestration via WP-CLI.';
	$lines[] = '';
	$lines[] = "Discover the full command surface: `{$wp} datamachine --help`. Always run `--help` on any subcommand to see its options.";
	$lines[] = '';

	foreach ( datamachine_agents_md_command_groups() as $command => $subcommands ) {
		$pipe = implode( '|', $subcommands );

		if ( '' !== $pipe ) {
			$lines[] = "- `{$wp} {$command} {$pipe}`";
		} else {
			$lines[] = "- `{$wp} {$command}`";
		}
	}

	$lines[] = '';
	$lines[] = 'Use `--help` on any command to discover options and subcommands.';

	return implode( "\n", $lines );
}

/**
 * Build the ordered command => subcommand-names map for the section.
 *
 * Reflects each command class via the shared CliCommandIntrospector (preferred)
 * and degrades to a local reflection fallback when the shared helper is
 * unavailable or lacks the method. De-duplicates by class so singular/plural
 * aliases that resolve to the same class document once, preserving the first
 * registered spelling.
 *
 * @return array<string, string[]> Command label => ordered subcommand names.
 */
function datamachine_agents_md_command_groups(): array {
	$groups = array();
	$seen   = array();

	foreach ( CommandRegistry::map() as $command => $command_class ) {
		if ( isset( $seen[ $command_class ] ) ) {
			continue;
		}
		$seen[ $command_class ] = true;

		$groups[ $command ] = datamachine_agents_md_subcommand_names( $command_class );
	}

	return $groups;
}

/**
 * Resolve a command class's subcommand names, preferring the shared helper.
 *
 * @param class-string $command_class Command class.
 * @return string[] Ordered subcommand names ('__default' omitted).
 */
function datamachine_agents_md_subcommand_names( string $command_class ): array {
	$introspector = '\\DataMachine\\Engine\\AI\\CliCommandIntrospector';

	if ( class_exists( $introspector ) && method_exists( $introspector, 'describe_class' ) ) {
		$subcommands = call_user_func( array( $introspector, 'describe_class' ), $command_class );
		$names       = array();
		foreach ( (array) $subcommands as $sub ) {
			$name = is_array( $sub ) ? ( $sub['name'] ?? '' ) : '';
			if ( '' === $name || '__default' === $name ) {
				continue;
			}
			$names[] = $name;
		}

		// describe_class returns [] for classes whose only subcommand is an
		// __invoke (flat invoke commands) on helper versions that predate
		// __invoke support (#2639). Fall back locally so those still document.
		if ( ! empty( $names ) ) {
			return $names;
		}
	}

	return datamachine_agents_md_reflect_subcommand_names( $command_class );
}

/**
 * Local reflection fallback for subcommand names.
 *
 * Context-safe: reflects over the class source without touching the live WP-CLI
 * runner. Mirrors WP-CLI's subcommand resolution — public, non-static,
 * own-declared methods; `@subcommand <name>` annotation wins over the method
 * name; magic methods are skipped except `__invoke`, which maps to the namespace
 * itself ('__default') and is therefore omitted from the documented list.
 *
 * @param class-string $command_class Command class.
 * @return string[] Ordered subcommand names.
 */
function datamachine_agents_md_reflect_subcommand_names( string $command_class ): array {
	if ( ! class_exists( $command_class ) ) {
		return array();
	}

	try {
		$reflection = new \ReflectionClass( $command_class );
	} catch ( \Throwable $e ) {
		return array();
	}

	$names = array();

	foreach ( $reflection->getMethods( \ReflectionMethod::IS_PUBLIC ) as $method ) {
		if ( $method->isStatic() ) {
			continue;
		}
		if ( $method->getDeclaringClass()->getName() !== $reflection->getName() ) {
			continue;
		}

		$method_name = $method->getName();
		$doc         = $method->getDocComment();
		$doc         = is_string( $doc ) ? $doc : '';

		$annotated = '';
		if ( preg_match( '/@subcommand\s+(\S+)/', $doc, $m ) ) {
			$annotated = $m[1];
		}

		if ( '__invoke' === $method_name && '' === $annotated ) {
			// Flat invoke command — the namespace itself, no sub-word.
			continue;
		}

		if ( '' !== $annotated ) {
			$names[] = $annotated;
			continue;
		}

		if ( 0 === strpos( $method_name, '__' ) ) {
			continue;
		}

		$names[] = str_replace( '_', '-', $method_name );
	}

	return $names;
}

/**
 * Resolve the WP-CLI command prefix for the current environment.
 *
 * @return string
 */
function datamachine_agents_md_wp_cli_cmd(): string {
	$parts = array( 'wp' );

	if ( function_exists( 'posix_geteuid' ) && 0 === posix_geteuid() ) {
		$parts[] = '--allow-root';
	}

	$abspath = rtrim( ABSPATH, '/' );
	if ( '/var/www/html' !== $abspath ) {
		$parts[] = '--path=' . $abspath;
	}

	return apply_filters( 'datamachine_wp_cli_cmd', implode( ' ', $parts ) );
}

// Sections register on `datamachine_sections` (fired lazily, once per request,
// when a composable file is generated). The AGENTS.md composable-file
// registration itself is wired alongside the other default memory files in
// datamachine_register_default_memory_files() (inc/bootstrap.php), mirroring how
// SITE.md / NETWORK.md register — so all default memory files share one
// registration path on `plugins_loaded`.
add_action( 'datamachine_sections', 'datamachine_register_agents_md_sections' );
